#!/bin/bash

# Generate config on demand
[ -n "$1" ] && [ "$1" == "-r" ] && \
    "$HOME/.local/bin/themer" --write-one .config/stalonetray/stalonetrayrc.template

# Terminate already running stalonetray instances
killall -q stalonetray

# Wait until the processes have been shut down
while pgrep -u $UID -x stalonetray >/dev/null; do sleep 1; done

# Launch tray
stalonetray -c "$XDG_CONFIG_HOME/stalonetray/stalonetrayrc" &
