#!/bin/bash

# Terminate already running sxhkd instances
killall -q sxhkd

# Wait until the processes have been shut down
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

FIFO_DIR="/tmp/sxhkd"
FIFO_PATH="${FIFO_DIR}/status"

[ -p "${FIFO_PATH}" ] && rm "${FIFO_PATH}"
mkdir -p $FIFO_DIR
mkfifo "${FIFO_PATH}"

sxhkd -m 1 -t 20 -s "${FIFO_PATH}" &
