#!/bin/bash

# Generate config
$HOME/.local/bin/themer --app-config $XDG_CONFIG_HOME/dunst/dunstrc

# Terminate already running dunst instances
killall -q dunst

# Wait until the processes have been shut down
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

# Launch dunst
dunst &
