#!/bin/bash

# Generate config on demand
[ ! -z "$1" ] && [ "$1" == "-r" ] && \
    $HOME/.local/bin/themer --template .config/dunst/dunstrc.template

# Terminate already running dunst instances
killall -q dunst

# Wait until the processes have been shut down
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

# Launch dunst
dunst &
