#!/bin/bash

# Generate config on demand
[ -n "$1" ] && [ "$1" == "-r" ] && \
    "$HOME/.local/bin/themer" --write-one .config/picom/config.template

# Terminate already running picom instances
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
#picom  --daemon --config ~/.config/picom/config
picom --daemon --config ~/.config/picom/config
