#!/bin/sh

#-------------------------------------------------------------------------------
# bspwm settings
#-------------------------------------------------------------------------------

# Monitors
bspc monitor DP-0 -d terminal terminal code code web music files misc
bspc monitor HDMI-0 -d terminal terminal code code misc

# Colors
bspc config normal_border_color     "#747C84"
bspc config focused_border_color    "#C795AE"
bspc config active_border_color     "#ADB3BA"
bspc config presel_feedback_color   "#C795AE"

# Windows
bspc config top_padding             0
bspc config border_width            0
bspc config window_gap              5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true
bspc config focus_follows_pointer   false
bspc config click_to_focus          button1
bspc config pointer_modifier        mod4

# Placement
bspc rule -a                        Code                desktop=^3
bspc rule -a                        jetbrains-idea-ce   desktop=^4
bspc rule -a                        Firefox             monitor=primary desktop=^5
bspc rule -a                        Google-chrome       desktop=^5
bspc rule -a                        Places              desktop=^5      state=floating
bspc rule -a                        Spotify             desktop=^7
bspc rule -a                        Gimp                desktop=^8      state=floating
bspc rule -a                        Wfica_Seamless      state=floating
bspc rule -a                        Nautilus            state=floating
bspc rule -a                        Vlc                 state=floating
bspc rule -a                        feh                 state=floating
bspc rule -a                        Yad                 state=floating
bspc rule -a                        Caffeine            state=floating
bspc rule -a                        Gucharmap           state=floating

#-------------------------------------------------------------------------------
# desktop environment
#-------------------------------------------------------------------------------

# Set wallpaper
~/.fehbg &

# Disk manager tray
udiskie -t &

# Notifications server
dunst &

# Start polybar to avoid conflicts with compton
~/.config/polybar/scripts/launch
