#!/bin/sh

#-------------------------------------------------------------------------------
# bspwm settings
#-------------------------------------------------------------------------------

# Load monitors info
source ~/.local/bin/monitorinfo

# Desktops
bspc monitor $PM_NAME -d home terminal terminal code code code web music chat misc
if [ -n "$LM_NAME" ]; then 
    bspc monitor $LM_NAME -d home terminal code code misc
fi

# Colors
bspc config normal_border_color   "#393F45"
bspc config focused_border_color  "#565E65"
bspc config active_border_color   "#565E65"
bspc config presel_feedback_color "#C795AE"

# Windows
bspc config border_width          2
bspc config top_padding           0
bspc config window_gap            5
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        false
bspc config focus_follows_pointer false
bspc config click_to_focus        button1
bspc config pointer_modifier      mod4

# Placement
bspc rule -a Code                    -o desktop=primary:^3
bspc rule -a jetbrains-idea          -o desktop=primary:^6
bspc rule -a Google-chrome           -o desktop=primary:^7
bspc rule -a Spotify                 -o desktop=primary:^8
bspc rule -a Slack                   -o desktop=primary:^9
bspc rule -a Gimp                    -o desktop=primary:^0 state=floating
bspc rule -a nautilus                -o state=floating
bspc rule -a KeePass2                -o state=floating
bspc rule -a vlc                     -o state=floating
bspc rule -a feh                     -o state=floating
bspc rule -a Yad                     -o state=floating
bspc rule -a sun-awt-X11-XDialogPeer -o state=floating

#-------------------------------------------------------------------------------
# desktop environment
#-------------------------------------------------------------------------------

# Set wallpaper
~/.fehbg &

# Start polybar to avoid conflicts with compton
 ~/.config/polybar/scripts/launch

# Start dunst notifications manager
~/.config/dunst/scripts/launch

# Start disk manager tray
~/.config/udiskie/scripts/launch
