#!/bin/bash

set -x

export PRIMARY_MONITOR=$(xrandr | awk '$3 == "primary" {print $1}')
export PRIMARY_MONITOR_RES=$(xrandr | awk '$3 == "primary" {getline; print $1}')

export LEFT_MONITOR=$(xrandr | awk '/connected [0-9]+x[0-9]+(\+|-)[0-9]+(\+|-)[0-9]+ left/ {print $1}')
export LEFT_MONITOR_RES=$(xrandr | awk '/connected [0-9]+x[0-9]+(\+|-)[0-9]+(\+|-)[0-9]+ left/ {getline; print $1}')
