#!/bin/bash

# Source bar info variables
. "$HOME/.local/bin/themer" --bar-info

# Generate config on demand
[ -n "$1" ] && [ "$1" == "-r" ] && \
    "$HOME/.local/bin/themer" --write-one .config/polybar/config.ini.template

# Hack for Polybar ARGB format
sed -i -E 's/([0-9a-fA-F]{2})#([0-9a-fA-F]{6})/#\1\2/g' "$XDG_CONFIG_HOME/polybar/config.ini"

# Terminate already running polybar instances
killall -q polybar
killall -q sxhkd-status

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd-status >/dev/null; do sleep 1; done

# Launch bars
polybar --log=warning top &
if [ -z "$PM_BAR_COMPACT" ]; then
    polybar --log=warning bottom-compact &
else
    polybar --log=warning bottom &
fi

[ -n "$LM_NAME" ] && polybar left &
[ -n "$RM_NAME" ] && polybar right &

# Launch sxhkd listener
"$XDG_CONFIG_HOME/polybar/scripts/sxhkd-status" &
