#!/bin/bash

# Load monitors info if not available
if [ -z "$PM_NAME" ]; then
    source ~/.local/bin/monitorinfo
fi

# Terminate already running polybar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bars
polybar top &
polybar bottom &
[ ! -z "$LM_NAME" ] && polybar left &
[ ! -z "$RM_NAME" ] && polybar right &

