#!/bin/bash

STATUS_LOG_FILE="/tmp/redshift/status.log"

function get_status() {
	[ -f "$STATUS_LOG_FILE" ] \
		&& tac $STATUS_LOG_FILE | tr -d '\000' | grep -i -m 1 status | cut -d ":" -f 2 | tr -d "[:blank:]" \
		|| echo "Disabled"
}

function get_polybar_text() {
	OUTPUT_TEMPL='%{F__COLOR__} __TEMP__%{F-}'
	COLOR=#65737e
	TEMP=$(get_status)

	if [ "$(pgrep -x redshift)" ] && [ "$TEMP" == "Enabled" ]; then
		TEMP=$(redshift -p 2> /dev/null | grep temp | cut -d ":" -f 2 | tr -dc "[:digit:]")

		if [ -z "$TEMP" ]; then
			COLOR=#65737e
		elif [ "$TEMP" -ge 5000 ]; then
			COLOR=#a3be8c
		elif [ "$TEMP" -ge 4000 ]; then
			COLOR=#ebcb8b
		else
			COLOR=#bf616a
		fi

		TEMP=${TEMP}k
	fi

	WITH_COLOR=${OUTPUT_TEMPL/__COLOR__/$COLOR}
	WITH_TEMP=${WITH_COLOR/__TEMP__/$TEMP}

	echo $WITH_TEMP
}

function toggle() {
	if [ "$(pgrep -x redshift)" ]; then
		echo "" > $STATUS_LOG_FILE
		pkill -USR1 redshift
	else
		$HOME/.config/redshift/launch
	fi
}

[ "$#" -lt 1 ] && echo "Missing parameters." && exit 1

case $1 in
"-p") get_polybar_text ;;
"-t") toggle ;;
*) echo "Invalid parameter." && exit 1 ;;
esac
