#!/bin/bash

STATUS_LOG_FILE="/tmp/redshift/status.log"
CONFIG_FILE="$XDG_CONFIG_HOME/redshift/config"

function get_status() {
	[ -f "$STATUS_LOG_FILE" ] \
		&& tac $STATUS_LOG_FILE | tr -d '\000' | grep -i -m 1 status | cut -d ":" -f 2 | tr -d "[:blank:]" \
		|| echo "Disabled"
}

function get_polybar_text() {
	OUTPUT_TEMPL='%{F__COLOR__}%{F-}  __TEMP__'
	COLOR=$1
	TEMP=$(get_status)

	if [ "$(pgrep -x redshift)" ] && [ "$TEMP" == "Enabled" ]; then
		TEMP=$(redshift -c $CONFIG_FILE -p 2> /dev/null | grep temp | cut -d ":" -f 2 | tr -dc "[:digit:]")

		if [ -z "$TEMP" ]; then
			COLOR=$1
		elif [ "$TEMP" -ge 5000 ]; then
			COLOR=$2
		elif [ "$TEMP" -ge 4000 ]; then
			COLOR=$3
		else
			COLOR=$4
		fi

		TEMP=${TEMP}k
	fi

	WITH_COLOR=${OUTPUT_TEMPL/__COLOR__/$COLOR}
	WITH_TEMP=${WITH_COLOR/__TEMP__/$TEMP}

	echo $WITH_TEMP
}

function toggle() {
	if [ "$(pgrep -x redshift)" ]; then
		echo "" > $STATUS_LOG_FILE
		pkill -USR1 redshift
	else
		$HOME/.config/redshift/launch
	fi
}

[ "$#" -lt 1 ] && echo "Missing parameters." && exit 1

case $1 in
'-p')
	[ "$#" -ne 5 ] && echo "Missing color codes." && exit 1
	get_polybar_text $2 $3 $4 $5
	;;
'-t')
	toggle
	;;
*)
	echo "Invalid parameter." && exit 1
	;;
esac
