#!/bin/bash

STATUS_FIFO="/tmp/sxhkd/status"

while read -r LINE <$STATUS_FIFO
do
  case $LINE in
  BBegin*)
    polybar-msg action "#sxhkd.hook.1"
    ;;
  EEnd*)
    polybar-msg action "#sxhkd.hook.0"
	  ;;
  esac
done
