#!/bin/bash

[ "$#" -lt 1 ] && echo "Missing parameters." && exit 1

SYSTEM_OUTPUT=$(checkupdates)
AUR_OUTPUT=$(trizen -Qu --aur)

SYSTEM_COUNT=$(echo "$SYSTEM_OUTPUT" | awk NF | wc -l)
AUR_COUNT=$(echo "$AUR_OUTPUT" | awk NF | wc -l)

case $1 in
"count") echo "${SYSTEM_COUNT}/${AUR_COUNT}" ;;
"gui")
    SYSTEM_HEADING="<big><b>System</b></big>"
    AUR_HEADING="<big><b>AUR</b></big>"
    GAP="\n\n"
    NO_UPDATES="No updates available"

    SYSTEM_DETAILS=$([ "$SYSTEM_COUNT" -gt 0 ] && echo "$SYSTEM_OUTPUT" || echo "$NO_UPDATES")
    AUR_DETAILS=$([ "$AUR_COUNT" -gt 0 ] && echo "$AUR_OUTPUT" || echo "$NO_UPDATES")

    yad --mouse --no-buttons --close-on-unfocus --borders=10 --text="${SYSTEM_HEADING}${GAP}${SYSTEM_DETAILS}${GAP}${AUR_HEADING}${GAP}${AUR_DETAILS}"
;;
*) echo "Invalid parameter." && exit 1 ;;
esac
