#!/bin/bash

source ~/.config/color_theme

NO_UPDATES="No updates available"
FAILED_QUERY="Could not query remote server"
SYSTEM_HEADING="<big><b>System</b></big>"
AUR_HEADING="<big><b>AUR</b></big>"
GAP="\n\n"

function count_lines() {
    echo $(echo "$1" | awk NF | wc -l)
}

function query() {
    OUTPUT=$($1 2>/dev/null)

    if [ $? -eq 0 ]; then
        # Fix for trizen which prints a message if there are no updates
        [ "$OUTPUT"  == ":: No AUR updates found..." ] && NUM=0 || NUM=$(count_lines $OUTPUT)

        [ "$NUM" -eq 0 ] && OUTPUT=$NO_UPDATES
    else
        NUM=$(count_lines "$OUTPUT")
        OUTPUT=$FAILED_QUERY        
    fi

    echo "COUNT=$NUM; OUTPUT=\"$OUTPUT\""
}

[ "$#" -lt 1 ] && echo "Missing parameters." && exit 1

case $1 in
"count")
    eval "$(query 'checkupdates')"
    STATUS=$COUNT
    
    eval "$(query 'trizen -Su --aur')"
    STATUS="${STATUS}/${COUNT}"
    
    echo " ${STATUS}"
;;
"gui")
    eval "$(query 'checkupdates')"
    SYSTEM_STATUS="${SYSTEM_HEADING}${GAP}${OUTPUT}"

    eval "$(query 'trizen -Su --aur')"
    AUR_STATUS="${SYSTEM_HEADING}${GAP}${OUTPUT}"

    yad --mouse --no-buttons --close-on-unfocus --borders=10 --text="${SYSTEM_STATUS}${GAP}${AUR_STATUS}"
;;
*) echo "Invalid parameter." && exit 1 ;;
esac
