#!/bin/bash

# Terminate already running barriers instances
killall -q barriers

# Wait until the processes have been shut down
while pgrep -u $UID -x barriers >/dev/null; do sleep 1; done

# Launch barriers
barriers -c $HOME/.config/barrier/barrier.conf --enable-crypto --no-restart --daemon
